# Generated by Django 6.1 on 2026-08-20 10:18

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The school admin who registered this school.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='max_grade',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='school',
            name='min_grade',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='school',
            name='parent_student_join_code',
            field=models.CharField(default=core.models.generate_join_code, help_text='Shared code parents type to register at this school.', max_length=12),
        ),
        migrations.AddField(
            model_name='school',
            name='student_join_code',
            field=models.CharField(default=core.models.generate_join_code, help_text='Shared code students type to register at this school.', max_length=12),
        ),
        migrations.CreateModel(
            name='TeacherInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(help_text='As entered by the admin, so the registering teacher can confirm this is their slot.', max_length=150)),
                ('assigned_grades', models.CharField(help_text="The grade or grade range this teacher is assigned, e.g. 'Grade 8' or 'Grades 8-12'.", max_length=50)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_invite', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_invites', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
