# Generated by Django 6.1 on 2026-08-19 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='International format, e.g. +27821234567. Only set for parents.', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Enter a phone number in international format, for example +27821234567.', regex='^\\+[1-9]\\d{7,14}$')]),
        ),
    ]
