# Generated by Django 6.1 on 2026-08-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('school_admin', 'School admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], help_text='Determines which dashboard this account can reach.', max_length=20),
        ),
    ]
