# Generated by Django 6.1 on 2026-08-13 23:36

import core.storage
import django.core.validators
import django.db.models.deletion
import marking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, help_text='Optional. Included in the prompt, which helps the model interpret notation in subjects like Mathematics.', max_length=100)),
                ('content', models.TextField(help_text='The marking guide: each question, the expected answer, and the marks available. Plain text is fine.')),
                ('total_marks', models.PositiveIntegerField(blank=True, help_text='Optional. Used only to sanity-check what the model returns.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorandums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=core.storage.papers_storage, upload_to=marking.models.paper_image_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('marked', 'Marked'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_kind', models.CharField(blank=True, choices=[('rate_limited', 'Rate limited by the AI provider'), ('no_credit', 'AI provider requires credit'), ('model_unavailable', 'Model unavailable'), ('service_error', 'AI provider error'), ('invalid_response', 'AI response could not be parsed'), ('image_error', 'Image could not be processed')], max_length=20)),
                ('failure_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memorandum', models.ForeignKey(help_text='Deleting a memorandum that has been marked against would orphan the results, so it is protected.', on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='marking.memorandum')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarkingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_awarded', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('marks_available', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('summary', models.TextField(blank=True, help_text='Plain-language overview. Sprint 7 sends this to parents.')),
                ('model_used', models.CharField(help_text='Which model produced this. Results are not comparable across models, so it is recorded per result rather than assumed.', max_length=120)),
                ('raw_response', models.TextField(blank=True, help_text="The model's unparsed reply, kept for debugging drift.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='marking.paper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('marks_awarded', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('marks_available', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(help_text='Why marks were lost and what to do about it, not just that the answer was wrong.')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Order the model returned them in.')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='marking.markingresult')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['status', '-created_at'], name='marking_pap_status_822b70_idx'),
        ),
    ]
