# Generated by Django 6.1 on 2026-08-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('marking', '0002_paper_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='assignment',
            field=models.ForeignKey(blank=True, help_text='The assignment this paper answers, if it was submitted for one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='classroom.assignment'),
        ),
    ]
