# Generated by Django 6.1 on 2026-08-19 21:20

from django.db import migrations, models


def backfill_subjects(apps, schema_editor):
    """Normalize every existing memorandum's subject.

    Blank subjects become "General" and mixed-case/whitespace ones are tidied,
    so no old record is left with a subject that would break the dashboard's
    grouping. Reuses the exact function the model uses, so the backfill and
    ongoing normalization can never drift apart.
    """
    from marking.models import normalize_subject

    Memorandum = apps.get_model("marking", "Memorandum")
    for memorandum in Memorandum.objects.all():
        normalized = normalize_subject(memorandum.subject)
        if normalized != memorandum.subject:
            memorandum.subject = normalized
            memorandum.save(update_fields=["subject"])


class Migration(migrations.Migration):

    dependencies = [
        ('marking', '0003_paper_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandum',
            name='subject',
            field=models.CharField(blank=True, default='General', help_text='Included in the marking prompt (it helps the model read subject notation) and used to group marks by subject on the progress dashboard. Normalized on save; defaults to General if left blank.', max_length=100),
        ),
        migrations.RunPython(backfill_subjects, migrations.RunPython.noop),
    ]
